# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
shared:
  image: vespaengine/vespa-build-centos-stream8:latest
  settings:
    email:
      addresses: [kraune@yahooinc.com]
      statuses: [SUCCESS, FAILURE]
  environment:
    USER_SHELL_BIN: bash

jobs:
  test-system-tests:
    requires: [~pr, ~commit]
    environment:
      USER_SHELL_BIN: bash
      RUBYLIB: $SD_SOURCE_DIR/lib
    steps:
      - install-deps: |
          set -e
          dnf module enable -y ruby:2.7
          dnf install -y \
              gcc-toolset-11-annobin \
              gcc-toolset-11-annobin-plugin-gcc \
              gcc-toolset-11-binutils \
              gcc-toolset-11-gcc-c++ \
              gcc-toolset-11-libatomic-devel \
              libxml2-devel \
              ruby \
              ruby-devel \
              rubygems-devel \
              rubygem-net-telnet \

          source /opt/rh/gcc-toolset-11/enable
          gem install libxml-ruby gnuplot distribution test-unit builder
      - run-tests: |
          cd ${RUBYLIB}
          ruby test/testrunner.rb
          exit $?

  systemtest-base-centos7:
    requires: [~pr, ~commit]
    sourcePaths: ["docker/"]
    annotations:
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/timeout: 30
      screwdriver.cd/buildPeriodically: H 4 * * 1
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: TURBO
      screwdriver.cd/dockerRam: TURBO
    secrets:
      - DOCKER_HUB_DEPLOY_KEY
    steps:
      - install-docker-cli: |
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          dnf -y install docker-ce docker-ce-cli containerd.io
          docker system info
      - build: |
          cd docker
          docker build --file Dockerfile.base \
                       --build-arg BASE_IMAGE=quay.io/centos/centos:stream8 \
                       --tag vespaengine/vespa-systemtest-base-centos-stream8:latest .
      - publish: |
          if [[ -z "$SD_PULL_REQUEST" ]]; then
            OPT_STATE="$(set +o)"
            set +x
            docker login --username aressem --password "$DOCKER_HUB_DEPLOY_KEY"
            eval "$OPT_STATE"
            docker push docker.io/vespaengine/vespa-systemtest-base-centos-stream8:latest
          fi
